Repository netlify/netlify-ipx, pull requests merged in 2022-06, with the labels that each got.

#11 feat: add support for NextJS remotePatterns
  README.md
  example/netlify/functions/ipx.ts
  package.json
  src/index.ts
  src/utils.ts
  yarn.lock
Labels: type: feature

#12 chore: add CODEOWNERS
  .github/CODEOWNERS
Labels: type: chore

#14 ci: enable renovate
  renovate.json
Labels: type: chore

#16 fix: remove content-type check
  src/http.ts
Labels: type: bug

#20 ci: add automation
  .github/.kodiak.toml
  .github/workflows/labeler.yml
Labels: type: chore

#31 ci: add release-please
  .github/workflows/release-please.yml
  package.json
  yarn.lock
Labels: type: chore

#41 CODEOWNERS update 202206
  .github/CODEOWNERS
Labels: type: chore

#42 fix: remote patterns logic
  example/netlify/functions/ipx.ts
  example/public/index.html
  src/index.ts
Labels: type: bug
