Repository netlify/netlify-ipx, pull requests merged in 2022-08, with the labels that each got.

#51 feat: support custom response headers
  README.md
  example/netlify/functions/ipx.ts
  netlify-ipx-v1.1.4.tgz
  src/index.ts
Labels: type: feature, automerge

#53 fix: remove tarball that was accidentally merged in
  netlify-ipx-v1.1.4.tgz
Labels: type: bug, automerge

#60 chore: added ava for testing
  .github/workflows/ci.yml
  package.json
  test/fake.test.ts
  yarn.lock
Labels: type: chore

#61 fix: x-forwarded-proto is sanitized now
  src/index.ts
Labels: type: bug

#63 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: type: security
